language: node_js

sudo: false

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'
  - '6'
  - '4'

before_script:
  - npm prune

script:
  - npm test

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
